### ISSUE TITLE
请问 数据库数据是如何利用gpt3.5 转换为问答对的？

### ISSUE THREAD

**Issue by shuoshuo0** [SCIR-HI/Med-ChatGLM#12]
请问 数据库数据如何利用gpt3.5转换为ChatGLM的训练数据（问答对）？程序中只提到了使用了gpt3.5结合了 prompt，并没有相关的代码，能否提供 数据库数据 到 问答对的细节代码？

**Comment by ZSitong** [comment]
同问，求大神指导

**Comment by s65b40** [comment]
您好，感谢您的关注，这方面的代码我们正在整理，未来可能通过一个新仓库进行发布，先和您大致描述一下我们的操作，输入给gpt3.5的内容为“知识：xxxx，请根据上述知识，生成关于xx的问题，并结合知识进行回答”，类似这样的形式
