### ISSUE TITLE
Tensors must have same number of dimensions: got 4 and 2

### ISSUE THREAD

**Issue by Hofanking** [SCIR-HI/Med-ChatGLM#13]
│ /root/autodl-tmp/tuning-chatglm/Med-ChatGLM/modeling_chatglm.py:1114 in chat                     │
│                                                                                                  │
│   1111 │   │   │   prompt += "[Round {}]\n问：{}\n答：".format(len(history), query)              │
│   1112 │   │   input_ids = tokenizer([prompt], return_tensors="pt", padding=True)                │
│   1113 │   │   input_ids = input_ids.to(self.device)                                             │
│ ❱ 1114 │   │   outputs = self.generate(**input_ids, **gen_kwargs)                                │
│   1115 │   │   outputs = outputs.tolist()[0][len(input_ids["input_ids"][0]):]                    │
│   1116 │   │   response = tokenizer.decode(outputs)                                              │
│   1117 │   │   response = response.strip()  

请问下，这个问题怎么解决？

**Comment by s65b40** [comment]
您好，请更新我们的仓库，如仍存在问题，请详细描述出现问题的前提，方便我们排查，谢谢
