### ISSUE TITLE
学长好，给您看一下我的测试结果，测到我怀疑人生

### ISSUE THREAD

**Issue by hangzeli08** [SCIR-HI/Med-ChatGLM#16]
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/104003969/234466956-8f3f337e-42fd-4b7a-a246-0fc8584862af.png">
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/104003969/234467036-850636eb-143a-4e4e-993d-e6b4f5c86f42.png">
我也是工大的，现在已经工作了，我知道你们的实力很强，一定是我弄错了，没弄明白应该怎么infer，可以帮我看出问题所在吗，用的原始代码没有修改，怎么解决重复词汇这么严重的情况啊

**Comment by misskey** [comment]
![image](https://user-images.githubusercontent.com/3667676/234548919-120cacd4-d42f-49d3-ab03-82f9836fb58b.png)
测的我也怀疑人生

**Comment by s65b40** [comment]
您好，感谢您的关注，当前模型的效果确实存在局限，尤其针对chatGLM这种训练过程比较完备的模型，我们的全量微调策略会在一定程度上带来性能下降，未来我们会尝试和华驼类似的lora微调。此外，模型当前的多轮对话能力有限，我们也会不断完善

**Comment by ray075hl** [comment]
> 您好，感谢您的关注，当前模型的效果确实存在局限，尤其针对chatGLM这种训练过程比较完备的模型，我们的全量微调策略会在一定程度上带来性能下降，未来我们会尝试和华驼类似的lora微调。此外，模型当前的多轮对话能力有限，我们也会不断完善

我也遇到了这个问题“我们的全量微调策略会在一定程度上带来性能下降”， 会导致模型忘记原有的日常知识
