### ISSUE TITLE
请问微调用了多久？

### ISSUE THREAD

**Issue by realcarlos** [SCIR-HI/Med-ChatGLM#17]

**Comment by s65b40** [comment]
您好，在80GBA100上大概需要几个小时，具体需要看一些超参设置，当前数据量最长不会超过1天

**Comment by Restry** [comment]
@s65b40 请问所有数据集都在[data](https://github.com/SCIR-HI/Med-ChatGLM/blob/main/data/train.txt)这里面吗？还有没有其它的没公开的内容？

**Comment by s65b40** [comment]
是的 公开的模型所需训练数据均在data里
