### ISSUE TITLE
mask_token相关报错

### ISSUE THREAD

**Issue by ayanesakura** [SCIR-HI/Med-ChatGLM#2]
File "Med-ChatGLM/modeling_chatglm.py", line 836, in forward
    mask_position = seq.index(mask_token)
ValueError: 150001 is not in list
看了下逻辑，
```
        if past_key_values is None:
            past_key_values = tuple([None] * len(self.layers))

            MASK, gMASK = 150000, 150001
            mask_token = MASK if MASK in input_ids else gMASK
            use_gmask = False if MASK in input_ids else gMASK
            seq = input_ids[0].tolist()

            mask_position = seq.index(mask_token)
```
这段代码似乎隐藏了一个assert，即`MASK in seq or gMASK in seq`,但看起来这个假设并不成立导致报错?

**Comment by exaggerated-dream** [comment]
官方更新太快。建议执行回滚huggingface代码版本解决。

**Comment by zhpmatrix** [comment]
> 您好，这个错误是chatglm和huggingface相关代码的更新导致的，我们会尽快修复并更新

请问这个bug有fix吗？在线等，挺急的，谢谢～
