### ISSUE TITLE
windows下会出现以下报错：

### ISSUE THREAD

**Issue by wudajun7509** [SCIR-HI/Med-ChatGLM#21]
File "C:\python code\Med-ChatGLM-main\modeling_chatglm.py", line 979, in prepare_inputs_for_generation
    mask_position = seq.index(mask_token)
ValueError: 130001 is not in list

**Comment by Zhang-star-master** [comment]
linux也有这个问题

**Comment by fxb392** [comment]
咋解决的？

**Comment by wudajun7509** [comment]
还没解决呢...

**Comment by fxb392** [comment]
MASK, gMASK = 150000, 150001就好了

**Comment by s65b40** [comment]
可能大家使用的相关依赖版本不同，当前仓库中的代码的是MASK, gMASK = 130000, 130001，如报错建议大家回退至第一版模型参数
