### ISSUE TITLE
Exception has occurred: ValueError 130001 is not in list

### ISSUE THREAD

**Issue by CyberFork** [SCIR-HI/Med-ChatGLM#25]
@modeling_chatglm.py line: 979
Exception has occurred: ValueError
130001 is not in list
  File "E:\OpenSourceModel\Med-ChatGLM-main\Med-ChatGLM-main\modeling_chatglm.py", line 979, in prepare_inputs_for_generation
    mask_position = seq.index(mask_token)
  File "E:\OpenSourceModel\Med-ChatGLM-main\Med-ChatGLM-main\modeling_chatglm.py", line 1114, in chat
    outputs = self.generate(**input_ids, **gen_kwargs)
  File "E:\OpenSourceModel\Med-ChatGLM-main\Med-ChatGLM-main\infer.py", line 12, in <module>
    response, history = model.chat(tokenizer, "问题：" + a.strip() + '\n答案：', max_length=256, history=[])
ValueError: 130001 is not in list

**Comment by panyuetj** [comment]
same error

**Comment by YRH0** [comment]
same error

**Comment by YRH0** [comment]
same error

**Comment by realalexsun** [comment]
同问，所有配置已准备好，模型成功加载，第一次提问后报错Exception has occurred: ValueError 130001 is not in list。

Same Error occurred after first query.

**Comment by SilenceWinter** [comment]
Same exception

**Comment by zhougz2018** [comment]
同上，这个是什么原因？

**Comment by CyberFork** [comment]
修改 modeling_chatglm.py 中的所有13000 为 15000.推荐使用批量替换.

或者通过 git log 查看到 commit 61471075ed222e6cb3cc9d4bf87c9a2809e117d1这个节点，回退回去即可。

**Comment by zh2010** [comment]
> 修改 modeling_chatglm.py 中的所有13000 为 15000.推荐使用批量替换.
> 
> 或者通过 git log 查看到 commit 61471075ed222e6cb3cc9d4bf87c9a2809e117d1这个节点，回退回去即可。
“修改 modeling_chatglm.py 中的所有13000 为 15000.推荐使用批量替换.”这个是写错了吧，里面没有13000，只有130000和130001，并且替换之后也不对，请再确认下？

**Comment by CyberFork** [comment]
> > 修改 modeling_chatglm.py 中的所有13000 为 15000.推荐使用批量替换.
> > 或者通过 git log 查看到 commit 61471075ed222e6cb3cc9d4bf87c9a2809e117d1这个节点，回退回去即可。
> > “修改 modeling_chatglm.py 中的所有13000 为 15000.推荐使用批量替换.”这个是写错了吧，里面没有13000，只有130000和130001，并且替换之后也不对，请再确认下？

130000和130001 不就是包含 13000？

**Comment by CyberFork** [comment]
> > 修改 modeling_chatglm.py 中的所有13000 为 15000.推荐使用批量替换.
> > 或者通过 git log 查看到 commit 61471075ed222e6cb3cc9d4bf87c9a2809e117d1这个节点，回退回去即可。
> > “修改 modeling_chatglm.py 中的所有13000 为 15000.推荐使用批量替换.”这个是写错了吧，里面没有13000，只有130000和130001，并且替换之后也不对，请再确认下？

通过 git log 查看到 commit 61471075ed222e6cb3cc9d4bf87c9a2809e117d1这个节点，回退回去吧，可能还有其他需要修改的
