### ISSUE TITLE
会遇到最后一句话不断重复的现象，这是什么原因造成的呢

### ISSUE THREAD

**Issue by fxb392** [SCIR-HI/Med-ChatGLM#29]
用户：阿莫西林主要治疗哪些病症？

阿莫西林主要治疗肺炎球菌病、肺炎、链球菌肺炎、青霉素过敏、青霉素过敏引起的肺炎、肺炎、青霉素过敏引起的肺炎、青霉素过敏引起的肺炎、青霉素过敏引起的肺炎、青霉素过敏引起的肺炎、青霉素过敏引起的肺炎、青霉素过敏引起的肺炎、青霉素过敏引起的肺炎、青霉素过敏引起的肺炎、青霉素过敏引起的肺炎、青霉素过敏引起的肺炎、青霉素过敏引起的肺炎、青霉素过敏引起的肺炎、青霉素过敏引起的肺炎、青霉素过敏引起的肺炎、青霉素过敏引起的肺炎、青霉素过敏引起的肺炎、青霉素过敏引起的肺炎、青霉素过敏引起的肺炎、青霉素过敏引起的肺炎、青霉素过敏引起的肺炎、青霉素过敏引起的肺炎、青霉素过敏引起的肺炎、青霉素过敏引起的肺炎、。

**Comment by s65b40** [comment]
大型生成模型目前在仅小规模指令微调后都或多或少存在这样的情况，可以尝试调整model.generate中的generate_config涉及重复生成的参数，可以缓解这个问题，从根本上解决这个问题需要后续更充分的训练和与人对齐等方法
