### ISSUE TITLE
请问一下医学知识库和数据集分别是指什么

### ISSUE THREAD

**Issue by swallowMuzi** [SCIR-HI/Med-ChatGLM#35]
数据集是train.txt文件
请问一下医学知识库是什么，是用在哪里的？
询问问题后，回答是基于医学知识库和数据集一起的吗？
医学知识会要求回答的准确性，请问一下怎么样去尽可能的保持回答的准确性？

一些疑惑，请教一下，谢谢！

**Comment by s65b40** [comment]
医学知识库是cMeKG，由于其使用要求，我们不可以对其进行开源，如有需要可以联系cMeKG的开发者。用途是结合知识生成更准确的问答对。准确性以自动化的方法没有办法完全保证，当前如果需要准确性，需要多名领域专家的同时标注。
