### ISSUE TITLE
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/MODEL_PATH/resolve/main/config.json

### ISSUE THREAD

**Issue by chenxu126** [SCIR-HI/Med-ChatGLM#37]
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/MODEL_PATH/resolve/main/config.json
有遇到这种情况的没？

**Comment by chenxu126** [comment]
修改名称并公开
想要使用自己的模型，必须将它设置为pulic，否则会报Unauthorized错误。如下：

requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/lambdarw/pret5-base-re-en/resolve/main/spiece.model
如果希望自己的模型更加有辨识度，方便记忆，也可以给模型修改一下名称。在settings标签页中，可以修改项目名称，删除项目，公开项目或私有项目，等等操作。
不知道怎么算修改名称并公开

**Comment by s65b40** [comment]
#40
和这个是一个问题，需要替换模型存储位置

**Comment by chenxu126** [comment]
> #40 和这个是一个问题，需要替换模型存储位置

谢谢楼主，我显卡是A6000，64G的设备，下载了百度云上的13G模型，收集了7000多问答，现在随后一个问题是显存不够，想下您微信行么，最后临门一脚实在过不去。13651233904，顶礼
