### ISSUE TITLE
微调自己数据集遇到账户之类的错误问题，请问怎么解决，实在不理解报错

### ISSUE THREAD

**Issue by chenxu126** [SCIR-HI/Med-ChatGLM#40]
![2](https://github.com/SCIR-HI/Med-ChatGLM/assets/19886457/559b6dbf-d06d-46ef-a2f5-6ed3e2fb7eed)

**Comment by s65b40** [comment]
您好，您需要将代码中的MODEL_PATH替换为您模型下载后的存储位置路径

**Comment by chenxu126** [comment]
多谢，已成功
