### ISSUE TITLE
6G显存问题和模型参数本地目录指向问题

### ISSUE THREAD

**Issue by radarfyh** [SCIR-HI/Med-ChatGLM#44]
1、我的显卡只有6G内存，请问怎么配置？（或者在哪个文件修改哪行代码）
2、模型参数ChatGLM-6B-Med下载到本地目录后，请问应该在哪里进行配置以便于指向它？

**Comment by s65b40** [comment]
1. 您好，这方面可能需要参考一下chatglm官方的相关介绍，我们这边还没有做过相关尝试
2. 您只需要修改代码中涉及模型的path即可
