### ISSUE TITLE
我用提供的train.txt文件微调完模型后，模型对于有些提问的回答出现了一直打印重复答案的问题

### ISSUE THREAD

**Issue by LCK-Lin** [SCIR-HI/Med-ChatGLM#7]
回答： 你好，欢迎来问我问题。
请输入您的问题：（输入q以退出）小明感染咽鼓管炎，有哪些临床症状和体征？
回答： 小明的临床症状和体征包括耳痛、耳痛、听力下降、耳鸣、听力下降、耳道流脓、耳痛、耳道流水、耳道流脓、耳痛、耳道流水、听力下降、耳道流脓、耳痛、听力下降、耳道流脓、耳痛、听力下降、耳道流脓、耳痛、听力下降、耳道流脓、耳痛、听力下降、耳道流脓、耳痛、听力下降、耳道流脓、耳痛、听力下降、耳道流脓、耳痛、听力下降、耳道流脓、耳痛、听力下降、耳道流脓、耳痛、听力下降、耳道流脓、耳痛、听力下降、耳道流脓、耳痛、听力下降、耳道流脓、耳痛、听力下降、耳道流脓、耳痛、听力下降、耳道流脓、耳痛、听力下降、耳道流脓、耳痛、听力下降、耳道流脓、耳痛、听力下降、耳道流脓、耳痛、听力下降、耳

**Comment by cutelitchi** [comment]
我也遇到这个情况

**Comment by s65b40** [comment]
#29
