### ISSUE TITLE
编程萌新求助如何运行该程序

### ISSUE THREAD

**Issue by Dr-Tumour** [SCIR-HI/Med-ChatGLM#8]
我是一个医学生，对编程没有太多知识储备，看到有人宣传这个想尝试一下，我安装了python3.11，cmd运行了pip install -r requirements.txt，下载并解压了code里面的压缩包，并把云盘里面的十多个g的参数放到了model文件夹里面了，但是在Med-ChatGLM-main目录里面用cmd运行python infer.py后，报ModuleNotFoundError: No module named 'torch'，是我操作有问题吗

**Comment by s65b40** [comment]
您好，请确定已安装好requirements中必要的环境，当前的error说明可能没有正确安装环境，

**Comment by JImmyHui2017** [comment]
建议先研究下原生的glm-6b , 关于pytorch的安装，看官网 https://pytorch.org/   , 或者试试直接命令行执行 `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`   注意这个安装过程可能受到跨境网络波动影响
